name: Lint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
      - name: Install dependencies
        run: |
          conda install -c conda-forge shellcheck
      - name: Shellcheck
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          shellcheck --format=gcc $(find . -iname "*.sh")
          echo "::remove-matcher owner=shellcheck::"
